---
# Autoscale Voteapp
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontalscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: votingapp
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
status:
  observedGeneration: 1
  lastScaleTime: 
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
