name: "Build et deploiement d'une image Docker"

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    
env:
  REGISTRY: ghrc.io
  IMAGE_NAME: ${{ github.repository }}
  


jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Connexion au registry de GitHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY }}
          
        - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
        - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/ryanob/brief-8:latest
          labels: ${{ steps.meta.outputs.labels }}
        

 

  
 
          
  deploy-infrastructure:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connexion au cluster kubernetes
        run: |
          mkdir ~/.kube/
          echo -e "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          
      - name: Connexion au cluster kubernetes
        run: |
          ls -la
          kubectl apply -f ./k8s/infrastructure.yml
          kubectl apply -f ./k8s/autoscaler.yml
          kubectl apply -f ./k8s/ingress.yml
