name: "Build et deploiement d'une image Docker"

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: set up docker environment
        uses: docker/setup-buildx-action@v1
        
      - name: Build Docker image
        run: docker build . --tag ghcr.io/RyanoB/brief-8:latest
        
      - name: Log in to Docker registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push docker/example-voting-app-vote:latest
 

  
 
          
  deploy-infrastructure:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Connexion au cluster kubernetes
        run: |
          mkdir ~/.kube/
          echo -e "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          
      - name: Connexion au cluster kubernetes
        run: |
          ls -la
          kubectl apply -f ./k8s/infrastructure.yml
          kubectl apply -f ./k8s/autoscaler.yml
          kubectl apply -f ./k8s/ingress.yml
